#!/usr/bin/env python
# -*- coding: utf-8 -*-


def try_me(your_question):
    if '?' in your_question:
        return 'Silly question, go to work!'


if __name__ == "__main__":
    your_question = 'hello?'
    print(try_me(your_question))
